name: Datree CLI
description: Use the Datree CLI in a github action
author: hadarco
inputs:
  path:
    description: the file/s to be tested
    required: true
  cli-arguments:
    description: the Datree CLI options to be used
    required: false
  is-helm-chart:
    description: is the desired file a Helm chart?
    required: true
    default: false
  helm-arguments:
    description: the Helm arguments to be used
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  icon: 'terminal'
  color: 'black'
